gui:
  nerdFontsVersion: "3"
  showRandomTip: false
  showIcons: true
  scrollHeight: 2
git:
  autoFetch: true
  paging:
    colorArg: always
    pager: "delta --dark --paging=never"
  merge:
    autoCommit: false
keybinding:
  universal:
    return: <esc>

